name: Comment on New PR

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the pull request
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const message = `
Hi @${prAuthor}, hope you're doing well!

Could you please add your name and the link to your contribution repo [here](https://github.com/OneDroid/.github)? This will display your profile on the organization's homepage. We truly appreciate all contributors and want to give proper credit for your awesome work.

Thanks a lot!
`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });